class MaintenanceRecord {
  // ID of the record (nullable because it may not be present when creating a new record)
  final int? id;
  // Type of service (e.g., "Oil Change", "Tire Rotation")
  final String serviceType;
  // Date the service was performed, formatted as a string (e.g., "2024-05-07")
  final String serviceDate;
  // Car's mileage at the time of service
  final int mileage;
  // Additional notes or comments about the service
  final String notes;

  // Constructor with named parameters; 'id' is optional, others are required
  MaintenanceRecord({
    this.id,
    required this.serviceType,
    required this.serviceDate,
    required this.mileage,
    required this.notes,
  });

  // Factory constructor to create an instance from a JSON map (usually from the backend)
  factory MaintenanceRecord.fromJson(Map<String, dynamic> json) {
    return MaintenanceRecord(
      id: json['id'], // Assigns ID if present (or null if not)
      serviceType: json['serviceType'] ?? "Unknown", // Fallback to "Unknown" if missing
      serviceDate: json['serviceDate']?.toString() ?? "Invalid date", // Safely convert to string
      mileage: json['mileage'] ?? 0, // Default mileage to 0 if missing
      notes: json['notes'] ?? "", // Default notes to empty string
    );
  }

  // Method to convert this Dart object into a JSON map (used for sending data to backend)
  Map<String, dynamic> toJson() => {
    'serviceType': serviceType,       // Include service type in JSON
    'serviceDate': serviceDate,       // Include service date
    'mileage': mileage,               // Include mileage
    'notes': notes,                   // Include notes
    // Note: 'id' is not included here since it's usually auto-generated by the backend
  };
}
